// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxkCTHvFBqXaHz4oFHwIS2MjMG2Ykn2s4',
    appId: '1:608962525480:web:c9cfde4e1eb3fde029f81d',
    messagingSenderId: '608962525480',
    projectId: 'vordil',
    authDomain: 'vordil.firebaseapp.com',
    storageBucket: 'vordil.appspot.com',
    measurementId: 'G-B659JJEC6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeG72w088_0dZ49H3G9xfU-umr6ZZPEJw',
    appId: '1:608962525480:android:9245a01030cf1b8529f81d',
    messagingSenderId: '608962525480',
    projectId: 'vordil',
    storageBucket: 'vordil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwaUGfxrd1upxYQWzliyeD9eBz7P1DTXI',
    appId: '1:608962525480:ios:604d69c99885716329f81d',
    messagingSenderId: '608962525480',
    projectId: 'vordil',
    storageBucket: 'vordil.appspot.com',
    iosClientId: '608962525480-2mcjauug6o4attdumldgi5obq71s1s8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.vordil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwaUGfxrd1upxYQWzliyeD9eBz7P1DTXI',
    appId: '1:608962525480:ios:604d69c99885716329f81d',
    messagingSenderId: '608962525480',
    projectId: 'vordil',
    storageBucket: 'vordil.appspot.com',
    iosClientId: '608962525480-2mcjauug6o4attdumldgi5obq71s1s8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.vordil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxkCTHvFBqXaHz4oFHwIS2MjMG2Ykn2s4',
    appId: '1:608962525480:web:80f683a012e763b529f81d',
    messagingSenderId: '608962525480',
    projectId: 'vordil',
    authDomain: 'vordil.firebaseapp.com',
    storageBucket: 'vordil.appspot.com',
    measurementId: 'G-7ZPDLW0PLN',
  );

}